# Generated by Django 4.0 on 2021-12-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat_wms', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='user.user'),
        ),
        migrations.AddField(
            model_name='centro',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.sociedad'),
        ),
        migrations.AddField(
            model_name='almacenes',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
    ]
