# Generated by Django 4.0 on 2021-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
    ]
