# Generated by Django 4.0.3 on 2022-03-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0004_delete_clientes_delete_flotilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='state',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='state',
        ),
        migrations.RemoveField(
            model_name='centro',
            name='state',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='state',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ubicaciones',
            name='state',
        ),
        migrations.AlterField(
            model_name='almacenes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
