# Generated by Django 4.0.3 on 2022-03-23 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0004_delete_clientes_delete_flotilla_and_more'),
        ('wms', '0002_remove_pedidos_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleentrada',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='detalleentrada',
            name='impresion_etiqueta',
        ),
        migrations.RemoveField(
            model_name='detalleentrada',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='f_arribo',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='f_descarga',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='placas',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='preveedor',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='usuario',
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_entregada',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_pedido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='nombre',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='entrada',
            field=models.ForeignKey(db_column='entrada_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='wms.entrada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='estatus',
            field=models.CharField(blank=True, choices=[('LIBRE', 'LIBRE'), ('CUARENTENA', 'CUARENTENA'), ('RECHAZO', 'RECHAZO')], default='LIBRE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='estatus_entrada',
            field=models.CharField(blank=True, choices=[('LIBRE', 'LIBRE'), ('CUARENTENA', 'CUARENTENA'), ('RECHAZO', 'RECHAZO')], default='LIBRE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='centro',
            field=models.ForeignKey(db_column='centro_id', on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estatus',
            field=models.CharField(blank=True, choices=[('LIBRE', 'LIBRE'), ('CUARENTENA', 'CUARENTENA'), ('RECHAZO', 'RECHAZO')], default='LIBRE', max_length=10, null=True),
        ),
    ]
