# Generated by Django 4.0.3 on 2022-03-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wms', '0004_delete_clientes_delete_flotilla_and_more'),
        ('wms', '0003_remove_detalleentrada_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='referencia',
        ),
        migrations.AddField(
            model_name='inventario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='centro',
            field=models.ForeignKey(blank=True, db_column='centro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_wms.centro'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='detalle_entrada',
            field=models.ForeignKey(db_column='detalle_entrada_id', on_delete=django.db.models.deletion.CASCADE, to='wms.detalleentrada'),
        ),
        migrations.AlterModelTable(
            name='detalleentrada',
            table='det_entrada',
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='det_pedido',
        ),
        migrations.AlterModelTable(
            name='entrada',
            table='dim_entrada',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='dim_inventario',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='dim_pedido',
        ),
    ]
