# Generated by Django 4.0.3 on 2022-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_alter_entrada_id_alter_inventario_centro_ubicaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantidadno_recuperada',
            new_name='cantidad_recuperada',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='observacion',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='articulo',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='docdocumento',
            new_name='doc_documento',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='docfactura',
            new_name='doc_factura',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidadrecuperada',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='recolectado',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='reposicion_u',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='id',
            field=models.AutoField(db_column='detalle_entrada_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(db_column='inventario_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id',
            field=models.AutoField(db_column='pedido_id', primary_key=True, serialize=False),
        ),
    ]
