# Generated by Django 4.0.3 on 2022-03-24 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_rename_cantidadno_recuperada_detallepedido_cantidad_recuperada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.AutoField(db_column='retorno_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('operador', models.CharField(max_length=100)),
                ('tipo_unidad', models.CharField(max_length=50, null=True)),
                ('placas', models.CharField(max_length=20, null=True)),
                ('observaciones', models.TextField()),
                ('fecha_reingreso', models.DateField(null=True)),
            ],
            options={
                'db_table': 'dim_retorno',
            },
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id',
            field=models.AutoField(db_column='detalle_pedido_id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id', models.AutoField(db_column='salida_id', primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=50)),
                ('tipo_unidad', models.CharField(max_length=100, null=True)),
                ('placas', models.CharField(max_length=20, null=True)),
                ('observaciones', models.CharField(max_length=20, null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.pedidos')),
            ],
            options={
                'db_table': 'dim_salida',
            },
        ),
    ]
